In [1]:
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
a = np.arange(1, 101)

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b = np.arange(501, 601)

In [5]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [6]:
train_test_split(a)

[array([  7,  76,  80,   4,  92,  98,  81,  90,  63,  25,  24,  58,  41,
         72,  84, 100,  48,  83,   2,  64,  23,  54,  18,  70,  21,  42,
         69,  45,  22,  15,  77,  94,  50,  46,  61,  96,  73,  36,  37,
         97,   5,  19,  87,  51,  10,  40,  67,  31,  86,  44,  16,  32,
         34,  11,  13,  85,  43,  29,  99,  39,  95,  71,  12,  49,  66,
         75,  20,  14,  74,  35,  82,  93,  56,  91,  57]),
 array([17, 27,  6, 55,  3,  8, 59, 53, 89, 30, 47, 79, 33,  1, 28, 78, 38,
        68,  9, 65, 52, 26, 88, 62, 60])]

In [34]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size = 0.2, shuffle = True, random_state = 42)

In [35]:
a_train.shape, a_test.shape, b_train.shape, b_test.shape

((80,), (20,), (80,), (20,))

In [32]:
a_train

array([ 38,  96,  18,  58,  70,   6,  66,   3,  82,   5,  76,   2,   9,
        12,  25,  37,  72,  61,  56,  75,  54,  90,  97,  16,  84,  83,
        10,  88, 100,  40,  65,  24,  11,  67,  60,  87,  42,  71,  98,
        34,  43,  46,  20,  22,  64,  23,  36,  45,  85,  95,   8,  49,
        86,  73,  19,  28,  68,  13,  92,  50,  31,  81,  57,   1,  89,
        94,  47,  33,  29,  63,  62,  51,  53,  17,  30,  14,   7,   4,
        35,  52])

In [27]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [36]:
b_train, b_test

(array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
        529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
        582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
        590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
        559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
        553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
        593, 552]),
 array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
        534, 591, 505, 577, 578, 513, 532]))